
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf0$\xf7\x16\xe8\x9b\xc2\xa0\xce\xeexRA95;'
    
_lr_action_items = {'TKString':([10,11,12,13,14,15,25,26,29,37,38,39,40,41,42,],[12,12,-20,15,15,-19,32,33,36,12,12,12,15,15,15,]),'TKSemicolon':([12,14,15,22,35,36,40,41,42,],[-20,17,-19,28,28,-13,-11,-10,-12,]),'TKExec':([29,],[37,]),'TKName':([0,1,2,3,4,5,6,7,8,9,12,15,16,17,18,20,23,24,27,28,29,30,31,34,35,36,40,41,42,],[1,5,1,8,-2,-18,8,-1,-17,11,-20,-19,18,-3,-18,-6,8,18,18,-9,38,-5,-4,-7,-8,-13,-11,-10,-12,]),'TKSplit':([29,],[39,]),'TKFinally':([12,15,16,20,24,27,28,30,34,35,36,40,41,42,],[-20,-19,19,-6,19,19,-9,-5,-7,-8,-13,-11,-10,-12,]),'TKOpenBracket':([12,13,15,],[-20,16,-19,]),'TKAssignment':([1,3,8,18,23,],[-18,9,-17,-18,29,]),'TKCloseBracket':([12,15,20,24,28,30,34,35,36,40,41,42,],[-20,-19,-6,31,-9,-5,-7,-8,-13,-11,-10,-12,]),'TKMinus':([5,6,8,],[-18,10,-17,]),'TKColon':([19,21,32,33,],[-16,27,-14,-15,]),'TKNotEquals':([18,],[26,]),'TKEquals':([18,],[25,]),'$end':([2,4,7,17,31,],[0,-2,-1,-3,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'guardedcommand':([16,24,27,],[20,30,34,]),'parameterlist':([10,11,37,38,39,],[13,14,40,41,42,]),'guard':([16,24,27,],[21,21,21,]),'program':([0,],[2,]),'command':([16,24,27,],[22,22,35,]),'valuelist':([0,1,2,16,24,27,],[3,6,3,23,23,23,]),'guardedcommandlist':([16,],[24,]),'procedure':([0,2,],[4,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program procedure','program',2,'p_program','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',100),
  ('program -> procedure','program',1,'p_program','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',101),
  ('procedure -> valuelist TKAssignment TKName parameterlist TKSemicolon','procedure',5,'p_procedure','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',108),
  ('procedure -> TKName valuelist TKMinus parameterlist TKOpenBracket guardedcommandlist TKCloseBracket','procedure',7,'p_procedure','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',109),
  ('guardedcommandlist -> guardedcommandlist guardedcommand','guardedcommandlist',2,'p_guardedcommandlist','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',116),
  ('guardedcommandlist -> guardedcommand','guardedcommandlist',1,'p_guardedcommandlist','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',117),
  ('guardedcommand -> guard TKColon guardedcommand','guardedcommand',3,'p_guardedcommand','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',125),
  ('guardedcommand -> guard TKColon command','guardedcommand',3,'p_guardedcommand','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',126),
  ('guardedcommand -> command TKSemicolon','guardedcommand',2,'p_guardedcommand','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',127),
  ('command -> valuelist TKAssignment TKName parameterlist','command',4,'p_command','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',136),
  ('command -> valuelist TKAssignment TKExec parameterlist','command',4,'p_command','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',137),
  ('command -> valuelist TKAssignment TKSplit parameterlist','command',4,'p_command','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',138),
  ('command -> valuelist TKAssignment TKString','command',3,'p_command','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',139),
  ('guard -> TKName TKEquals TKString','guard',3,'p_guard','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',147),
  ('guard -> TKName TKNotEquals TKString','guard',3,'p_guard','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',148),
  ('guard -> TKFinally','guard',1,'p_guard','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',149),
  ('valuelist -> valuelist TKName','valuelist',2,'p_valuelist','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',157),
  ('valuelist -> TKName','valuelist',1,'p_valuelist','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',158),
  ('parameterlist -> parameterlist TKString','parameterlist',2,'p_parameterlist','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',166),
  ('parameterlist -> TKString','parameterlist',1,'p_parameterlist','D:\\Code\\prog_ss_2014\\Interpreter_Python\\Interpreter\\lexerparser.py',167),
]
